### PR TITLE
Add nav position.

### PR DESCRIPTION
**Pull request by Irsanarisandy**
Implement nav position option: https://github.com/ganlanyuan/tiny-slider#options

### CODE REVIEW

**Comment by viktorlarsson** [comment]
Some merge request, could you rebase with master?

**Comment by Irsanarisandy** [comment]
Done

**Comment by Irsanarisandy** [comment]
Done, soz pressed wrong button

**Comment by Irsanarisandy** [comment]
Done

**Comment by aldarund** [comment]
@viktorlarsson merge please :)

**Comment by martin-badin** [comment]
Please update Readme too.

**Comment by viktorlarsson** [comment]
Thanks!

**Pull request merged**
